# Generated by Django 4.1 on 2023-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(default='06/03/2023', null=True, verbose_name='Fecha de nacimiento (dd/mm/aaaa)'),
        ),
    ]
