# Generated by Django 4.1 on 2023-03-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
