# Generated by Django 4.1 on 2023-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nombre_usuario',
            new_name='username',
        ),
    ]
