# Generated by Django 4.1 on 2023-03-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_nombre_usuario_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
