# Generated by Django 4.1 on 2023-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=264, verbose_name='Nombre')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha cuenta creada')),
                ('email', models.EmailField(max_length=264, unique=True, verbose_name='Correo electronico')),
                ('genero', models.CharField(max_length=64, verbose_name='Genero')),
                ('provincia', models.CharField(max_length=264, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=264, verbose_name='Ciudad')),
                ('disponibilidad', models.CharField(max_length=264)),
                ('lugar_comida', models.CharField(max_length=264)),
                ('musica', models.CharField(max_length=264)),
                ('musica_relax', models.CharField(max_length=264)),
                ('musica_animada', models.CharField(max_length=264)),
                ('salir', models.CharField(max_length=264)),
                ('actividades', models.CharField(max_length=264)),
                ('latitud', models.CharField(max_length=264)),
                ('longitud', models.CharField(max_length=264)),
                ('activo', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
