# Generated by Django 4.1 on 2023-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscoAmigosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actividades',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(max_length=264, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disponibilidad',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=264, null=True, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(max_length=64, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitud',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitud',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lugar_comida',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='musica',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='musica_animada',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='musica_relax',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provincia',
            field=models.CharField(max_length=264, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salir',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
