# Generated by Django 4.1 on 2023-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buscoAmigosApp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=264, verbose_name='Nombre')),
                ('fecha_creacion', models.DateField(default='YYYY-MM-DD', verbose_name='Fecha cuenta creada')),
                ('email', models.EmailField(max_length=264, null=True, unique=True, verbose_name='Correo electronico')),
            ],
        ),
    ]
