# Generated by Django 4.1 on 2023-03-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscoAmigosApp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
